I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 168, in script
Exception: Parameter 'new_widget' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/raim/Documents/renpy-6.17.3-sdk/renpy/execution.py", line 294, in run
    node.execute()
  File "/home/raim/Documents/renpy-6.17.3-sdk/renpy/ast.py", line 1163, in execute
    renpy.exports.with_statement(trans, paired)
  File "/home/raim/Documents/renpy-6.17.3-sdk/renpy/exports.py", line 1147, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/home/raim/Documents/renpy-6.17.3-sdk/renpy/display/core.py", line 1662, in do_with
    clear=clear)
  File "/home/raim/Documents/renpy-6.17.3-sdk/renpy/display/core.py", line 1993, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "/home/raim/Documents/renpy-6.17.3-sdk/renpy/display/core.py", line 2196, in interact_core
    new_widget=layers_root)
  File "/home/raim/Documents/renpy-6.17.3-sdk/renpy/atl.py", line 303, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'new_widget' is not known by ATL Transform.

Linux-3.2.0-23-generic-i686-with-debian-wheezy-sid
Ren'Py 6.17.3.327
Convivencia_Violencia 0.0
